# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.wars_esi_api import WarsEsiApi


class TestWarsEsiApi(unittest.TestCase):
    """WarsEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WarsEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_wars(self) -> None:
        """Test case for get_wars

        List wars
        """
        pass

    def test_get_wars_war_id(self) -> None:
        """Test case for get_wars_war_id

        Get war information
        """
        pass

    def test_get_wars_war_id_killmails(self) -> None:
        """Test case for get_wars_war_id_killmails

        List kills for a war
        """
        pass


if __name__ == '__main__':
    unittest.main()
