# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.sovereignty_esi_api import SovereigntyEsiApi


class TestSovereigntyEsiApi(unittest.TestCase):
    """SovereigntyEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SovereigntyEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_sovereignty_campaigns(self) -> None:
        """Test case for get_sovereignty_campaigns

        List sovereignty campaigns
        """
        pass

    def test_get_sovereignty_map(self) -> None:
        """Test case for get_sovereignty_map

        List sovereignty of systems
        """
        pass

    def test_get_sovereignty_structures(self) -> None:
        """Test case for get_sovereignty_structures

        List sovereignty structures
        """
        pass


if __name__ == '__main__':
    unittest.main()
