# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.skills_esi_api import SkillsEsiApi


class TestSkillsEsiApi(unittest.TestCase):
    """SkillsEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SkillsEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_characters_character_id_attributes(self) -> None:
        """Test case for get_characters_character_id_attributes

        Get character attributes
        """
        pass

    def test_get_characters_character_id_skillqueue(self) -> None:
        """Test case for get_characters_character_id_skillqueue

        Get character's skill queue
        """
        pass

    def test_get_characters_character_id_skills(self) -> None:
        """Test case for get_characters_character_id_skills

        Get character skills
        """
        pass


if __name__ == '__main__':
    unittest.main()
