# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.alliance_esi_api import AllianceEsiApi


class TestAllianceEsiApi(unittest.TestCase):
    """AllianceEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AllianceEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_alliances(self) -> None:
        """Test case for get_alliances

        List all alliances
        """
        pass

    def test_get_alliances_alliance_id(self) -> None:
        """Test case for get_alliances_alliance_id

        Get alliance information
        """
        pass

    def test_get_alliances_alliance_id_corporations(self) -> None:
        """Test case for get_alliances_alliance_id_corporations

        List alliance's corporations
        """
        pass

    def test_get_alliances_alliance_id_icons(self) -> None:
        """Test case for get_alliances_alliance_id_icons

        Get alliance icon
        """
        pass


if __name__ == '__main__':
    unittest.main()
