# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.calendar_esi_api import CalendarEsiApi


class TestCalendarEsiApi(unittest.TestCase):
    """CalendarEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_characters_character_id_calendar(self) -> None:
        """Test case for get_characters_character_id_calendar

        List calendar event summaries
        """
        pass

    def test_get_characters_character_id_calendar_event_id(self) -> None:
        """Test case for get_characters_character_id_calendar_event_id

        Get an event
        """
        pass

    def test_get_characters_character_id_calendar_event_id_attendees(self) -> None:
        """Test case for get_characters_character_id_calendar_event_id_attendees

        Get attendees
        """
        pass

    def test_put_characters_character_id_calendar_event_id(self) -> None:
        """Test case for put_characters_character_id_calendar_event_id

        Respond to an event
        """
        pass


if __name__ == '__main__':
    unittest.main()
