# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.routes_esi_api import RoutesEsiApi


class TestRoutesEsiApi(unittest.TestCase):
    """RoutesEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutesEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_route_origin_destination(self) -> None:
        """Test case for get_route_origin_destination

        Get route
        """
        pass


if __name__ == '__main__':
    unittest.main()
