# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.contacts_esi_api import ContactsEsiApi


class TestContactsEsiApi(unittest.TestCase):
    """ContactsEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactsEsiApi()

    def tearDown(self) -> None:
        pass

    def test_delete_characters_character_id_contacts(self) -> None:
        """Test case for delete_characters_character_id_contacts

        Delete contacts
        """
        pass

    def test_get_alliances_alliance_id_contacts(self) -> None:
        """Test case for get_alliances_alliance_id_contacts

        Get alliance contacts
        """
        pass

    def test_get_alliances_alliance_id_contacts_labels(self) -> None:
        """Test case for get_alliances_alliance_id_contacts_labels

        Get alliance contact labels
        """
        pass

    def test_get_characters_character_id_contacts(self) -> None:
        """Test case for get_characters_character_id_contacts

        Get contacts
        """
        pass

    def test_get_characters_character_id_contacts_labels(self) -> None:
        """Test case for get_characters_character_id_contacts_labels

        Get contact labels
        """
        pass

    def test_get_corporations_corporation_id_contacts(self) -> None:
        """Test case for get_corporations_corporation_id_contacts

        Get corporation contacts
        """
        pass

    def test_get_corporations_corporation_id_contacts_labels(self) -> None:
        """Test case for get_corporations_corporation_id_contacts_labels

        Get corporation contact labels
        """
        pass

    def test_post_characters_character_id_contacts(self) -> None:
        """Test case for post_characters_character_id_contacts

        Add contacts
        """
        pass

    def test_put_characters_character_id_contacts(self) -> None:
        """Test case for put_characters_character_id_contacts

        Edit contacts
        """
        pass


if __name__ == '__main__':
    unittest.main()
