# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.clones_esi_api import ClonesEsiApi


class TestClonesEsiApi(unittest.TestCase):
    """ClonesEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClonesEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_characters_character_id_clones(self) -> None:
        """Test case for get_characters_character_id_clones

        Get clones
        """
        pass

    def test_get_characters_character_id_implants(self) -> None:
        """Test case for get_characters_character_id_implants

        Get active implants
        """
        pass


if __name__ == '__main__':
    unittest.main()
