# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.loyalty_esi_api import LoyaltyEsiApi


class TestLoyaltyEsiApi(unittest.TestCase):
    """LoyaltyEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoyaltyEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_characters_character_id_loyalty_points(self) -> None:
        """Test case for get_characters_character_id_loyalty_points

        Get loyalty points
        """
        pass

    def test_get_loyalty_stores_corporation_id_offers(self) -> None:
        """Test case for get_loyalty_stores_corporation_id_offers

        List loyalty store offers
        """
        pass


if __name__ == '__main__':
    unittest.main()
