# coding: utf-8

"""
    EVE Stellar Information (ESI) - tranquility

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_api_client.api.dogma_esi_api import DogmaEsiApi


class TestDogmaEsiApi(unittest.TestCase):
    """DogmaEsiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DogmaEsiApi()

    def tearDown(self) -> None:
        pass

    def test_get_dogma_attributes(self) -> None:
        """Test case for get_dogma_attributes

        Get attributes
        """
        pass

    def test_get_dogma_attributes_attribute_id(self) -> None:
        """Test case for get_dogma_attributes_attribute_id

        Get attribute information
        """
        pass

    def test_get_dogma_dynamic_items_type_id_item_id(self) -> None:
        """Test case for get_dogma_dynamic_items_type_id_item_id

        Get dynamic item information
        """
        pass

    def test_get_dogma_effects(self) -> None:
        """Test case for get_dogma_effects

        Get effects
        """
        pass

    def test_get_dogma_effects_effect_id(self) -> None:
        """Test case for get_dogma_effects_effect_id

        Get effect information
        """
        pass


if __name__ == '__main__':
    unittest.main()
